messages:
  player without permission uses /afk:
    - "&7You dont have permission to use this plugin"
  admin afk on all players:
    - "§fIs now AFK"
  admin afk off all players:
    - "§fIs no longer AFK"
  player get kick because afk screen:
    - "You have been kicked because you were afk"
  before kick:
    - "Move or you will be kicked"
worlds where kick will not work:
  - "spawm"

time before kick:
  - 20

reminder before kick:
  - 15

afk permissions:
  - "helper"
  - "mod"
  - "dev"
  - "admin"
  - "opiekun"
  - "root"

opiekunowie:
  - "Andrzej"
  - "Staszek"
  - "Wiesia"